#!/usr/bin/env python3
"""
LDV-data converter for all angles (parameterized for speech or white noise).

This script generalizes the Stage 0 (WAV→NPY) extraction to support
either white noise (segment2; indices typically [538,539,540]) or speech
(segment1; indices provided via manifest or CLI), cutting identical
intervals from standard_file.wav and angle-specific LDV recordings.

Key features:
- Reads LDV-data_test_log.txt for segment1 time_len to compute the segment2 offset.
- Recomputes intervals from standard_file.wav with librosa (top_db=70, padding=0,
  min_duration=0.8) for reproducibility and validation.
- Accepts indices via --manifest (preferred) or --interval_indices.
- Writes outputs to speech_*_data_no_edge/ or white_noise_*_data_no_edge/
  mirroring existing folder structure used downstream.

No silent fallbacks: raises on missing files, SR mismatch, or invalid indices.

Usage examples:
  # Using a manifest generated by generate_speech_intervals_manifest.py
  python scripts/conversion/ldv_converter_all_angles_param.py \
    --dataset_path ~/LDV-data --material box \
    --audio_type speech --manifest results/speech_intervals.json \
    --output_dir ~/LDV-data-processed

  # Using explicit indices for white noise
  python scripts/conversion/ldv_converter_all_angles_param.py \
    --dataset_path ~/LDV-data --material IrregularBox \
    --audio_type white_noise --interval_indices 538,539,540 \
    --output_dir ~/LDV-data-processed
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Dict, Tuple

import librosa
import numpy as np
import soundfile as sf


@dataclass
class Interval:
    start: int
    end: int

    @property
    def duration(self) -> int:
        return self.end - self.start


def parse_time_len_to_ms(time_str: str) -> int:
    h, m, s = time_str.split(":")
    if "." in s:
        sec, ms = s.split(".")
        total_ms = (int(h) * 3600 + int(m) * 60 + int(sec)) * 1000 + int(ms.ljust(3, "0"))
    else:
        total_ms = (int(h) * 3600 + int(m) * 60 + int(s)) * 1000
    return total_ms


def split_intervals(y: np.ndarray, sr: int, top_db: float, padding_sec: float, min_duration_sec: float) -> List[Interval]:
    raw = librosa.effects.split(y, top_db=top_db)
    pad = int(padding_sec * sr)
    out: List[Interval] = []
    for s, e in raw:
        ns = max(0, s - pad)
        ne = min(len(y), e + pad)
        if (ne - ns) / sr >= min_duration_sec:
            out.append(Interval(ns, ne))
    return out


def find_degrees(complete_dir: Path, material: str, segment: str) -> List[int]:
    # pattern: {material}_degDDD_segmentS_complete.wav (DDD 3 digits, S=1|2)
    pat = re.compile(rf"^{re.escape(material)}_deg(\d{{3}})_segment{re.escape(segment[-1])}_complete\.wav$")
    degs = []
    for f in complete_dir.iterdir():
        if not f.is_file():
            continue
        m = pat.match(f.name)
        if m:
            degs.append(int(m.group(1)))
    return sorted(degs)


def save_original_segments(out_root: Path, prefix: str, indices: List[int], intervals: List[Interval], y: np.ndarray, sr: int) -> None:
    out_dir = out_root / f"{prefix}_original_data_no_edge"
    out_dir.mkdir(parents=True, exist_ok=True)
    for i, idx in enumerate(indices):
        iv = intervals[idx]
        seg = y[iv.start:iv.end]
        np.save(out_dir / f"original_clip_{i:03d}.npy", seg.astype(np.float32))
        sf.write(out_dir / f"original_clip_{i:03d}.wav", seg, sr)

    meta = {
        "dataset_info": {
            "source": "LDV standard_file.wav",
            "type": "original_playback",
            "conversion": "Stage0-WAV2NPY",
            "clips": len(indices),
        },
        "audio_info": {
            "sample_rate": int(sr),
            "interval_indices": indices,
        },
    }
    (out_dir / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")


def save_material_segments(out_root: Path, prefix: str, material: str, degrees: List[int], indices: List[int], intervals: List[Interval], y_path_fn, sr: int, segment: str, offset_samples: int) -> None:
    # out dir: {prefix}_{material.lower()}_data_no_edge/angle_<deg>/
    out_dir = out_root / f"{prefix}_{material.lower()}_data_no_edge"
    out_dir.mkdir(parents=True, exist_ok=True)

    # save per-angle clips
    for deg in degrees:
        angle_dir = out_dir / f"angle_{deg}"
        angle_dir.mkdir(parents=True, exist_ok=True)
        # load complete file for this degree
        y, ysr = librosa.load(str(y_path_fn(deg)), sr=None)
        if ysr != sr:
            raise RuntimeError(f"Sample rate mismatch: standard_file sr={sr}, {material} deg{deg:03d} sr={ysr}")

        for ci, idx in enumerate(indices):
            iv = intervals[idx]
            s = iv.start + offset_samples
            e = iv.end + offset_samples
            if s < 0 or e > len(y):
                raise RuntimeError(f"Interval out of bounds for {material} deg{deg:03d} {segment}: [{s},{e}) len={len(y)}")
            seg = y[s:e]
            np.save(angle_dir / f"clip_{ci:03d}.npy", seg.astype(np.float32))
            sf.write(angle_dir / f"clip_{ci:03d}.wav", seg, sr)

    # metadata
    meta = {
        "dataset_info": {
            "source": "LDV complete recordings",
            "material": material,
            "type": "LDV_recorded",
            "conversion": "Stage0-WAV2NPY",
            "total_angles": len(degrees),
            "clips_per_angle": len(indices),
            "segment": segment,
        },
        "angle_mapping": {f"angle_{d}": f"{d:03d}°" for d in degrees},
        "audio_info": {
            "sample_rate": int(sr),
            "interval_indices": indices,
        },
    }
    (out_dir / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="LDV-data converter for speech or white noise")
    ap.add_argument("--dataset_path", type=str, default=str(Path.home() / "LDV-data"), help="LDV-data root path")
    ap.add_argument("--material", type=str, choices=["box", "IrregularBox"], required=True, help="Material to process")
    ap.add_argument("--audio_type", type=str, choices=["speech", "white_noise"], default="speech", help="Audio type to extract")
    ap.add_argument("--segment", type=str, choices=["segment1", "segment2"], default=None, help="Override segment to use")
    ap.add_argument("--manifest", type=str, default=None, help="JSON manifest with indices and segment")
    ap.add_argument("--interval_indices", type=str, default=None, help="Comma-separated global interval indices (e.g., 538,539,540)")
    ap.add_argument("--output_dir", type=str, required=True, help="Output directory for dataset folders")
    ap.add_argument("--dataset_prefix", type=str, default=None, help="Override dataset prefix (default: 'speech' or 'white_noise')")
    ap.add_argument("--top_db", type=float, default=70.0, help="Split top_db threshold")
    ap.add_argument("--padding", type=float, default=0.0, help="Split padding seconds")
    ap.add_argument("--min_duration", type=float, default=0.8, help="Min interval duration seconds")
    args = ap.parse_args()

    dataset_path = Path(args.dataset_path).expanduser()
    complete_dir = dataset_path / "complete"
    test_log_path = dataset_path / "LDV-data_test_log.txt"
    standard_file = dataset_path / "standard_file.wav"
    if not complete_dir.exists():
        raise FileNotFoundError(f"Missing complete/ under {dataset_path}")
    if not standard_file.exists():
        raise FileNotFoundError(f"Missing standard_file.wav under {dataset_path}")
    if not test_log_path.exists():
        raise FileNotFoundError(f"Missing LDV-data_test_log.txt under {dataset_path}")

    info = json.loads(test_log_path.read_text(encoding="utf-8"))
    if "Audio" not in info or "segment1" not in info["Audio"]:
        raise ValueError("LDV-data_test_log.txt missing Audio.segment1 metadata")
    seg1_end_ms = parse_time_len_to_ms(info["Audio"]["segment1"]["time_len"])

    # Load standard file and compute intervals
    std_y, sr = librosa.load(str(standard_file), sr=None)
    intervals = split_intervals(std_y, sr, args.top_db, args.padding, args.min_duration)
    if not intervals:
        raise RuntimeError("No intervals found in standard_file.wav; adjust splitting params")

    # Resolve indices and segment
    if args.segment is not None:
        segment = args.segment
    else:
        segment = "segment1" if args.audio_type == "speech" else "segment2"

    indices: List[int]
    if args.manifest:
        manifest = json.loads(Path(args.manifest).expanduser().read_text(encoding="utf-8"))
        indices = list(map(int, manifest.get("indices", [])))
        man_seg = manifest.get("segment")
        if not indices:
            raise ValueError("Manifest missing non-empty 'indices'")
        if man_seg and man_seg != segment:
            raise ValueError(f"Segment mismatch: --segment={segment} vs manifest.segment={man_seg}")
    elif args.interval_indices:
        indices = [int(x.strip()) for x in args.interval_indices.split(",") if x.strip()]
        if not indices:
            raise ValueError("--interval_indices provided but empty after parsing")
    else:
        # Default only for white_noise with typical indices
        if args.audio_type == "white_noise":
            indices = [538, 539, 540]
        else:
            raise ValueError("Provide --manifest or --interval_indices for speech")

    # Validate indices
    n_iv = len(intervals)
    bad = [i for i in indices if i < 0 or i >= n_iv]
    if bad:
        raise IndexError(f"Invalid indices {bad} for intervals length {n_iv}")

    # Prepare outputs
    out_root = Path(args.output_dir).expanduser()
    out_root.mkdir(parents=True, exist_ok=True)

    # Prefix by audio type
    prefix = args.dataset_prefix or ("speech" if args.audio_type == "speech" else "white_noise")

    # Save original playback segments
    save_original_segments(out_root, prefix, indices, intervals, std_y, sr)

    # Determine offset samples for selected segment
    if segment == "segment1":
        offset_samples =  0
    else:
        offset_samples = int(seg1_end_ms / 1000.0 * sr)

    # Find available degrees for material/segment
    degrees = find_degrees(complete_dir, args.material, segment)
    if not degrees:
        raise RuntimeError(f"No files found for material={args.material}, segment={segment} under {complete_dir}")

    # Helper to construct file path
    def y_path_fn(deg: int) -> Path:
        return complete_dir / f"{args.material}_deg{deg:03d}_{segment}_complete.wav"

    # Save LDV recorded segments
    save_material_segments(out_root, prefix, args.material, degrees, indices, intervals, y_path_fn, sr, segment, offset_samples)

    print("Conversion completed successfully.")
    print(f"Audio type: {args.audio_type}, segment: {segment}, indices: {indices}")
    print(f"Angles processed ({len(degrees)}): {degrees[:6]}{'...' if len(degrees) > 6 else ''}")
    print(f"Output roots under: {out_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
