#!/usr/bin/env python3
"""
Run end-to-end NMF DOA localization using pre-computed transfer functions.

This CLI wires together the existing pipeline to evaluate DOA accuracy
on a speech dataset given a TF file generated by scripts/estimate_transfer_functions.py.
"""

import argparse
import logging
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from nmf_localizer import NMFLocalizationPipeline, NMFConfig


def setup_logging(verbose: bool = False):
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[logging.StreamHandler(sys.stdout)],
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run NMF DOA localization with pre-computed transfer functions",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Required paths
    p.add_argument('--tf-path', required=True, type=str, help='Path to transfer functions .pth file')
    p.add_argument('--speech-data-root', required=True, type=str, help='Root of speech dataset (angle_*/ subdirs)')
    p.add_argument('--output', required=True, type=str, help='Output directory for experiment results')
    
    # Optional separate data sources for USM training vs testing
    p.add_argument('--usm-data-root', type=str, default=None, help='Root of USM training dataset (if different from speech-data-root)')
    p.add_argument('--test-data-root', type=str, default=None, help='Root of test dataset (if different from speech-data-root)')
    p.add_argument('--usm-path', type=str, default=None, help='Path to pre-trained USM model .pth file (optional, skips USM training)')
    p.add_argument('--use-all-angles-for-usm', action='store_true', help='Use all angles for USM training (default: only 90deg)')

    # NMF / evaluation parameters
    p.add_argument('--beta', type=float, default=0.0, help='Beta divergence (0: IS, 1: KL, 2: L2)')
    p.add_argument('--lambda-group', type=float, default=5.0, help='Group sparsity weight')
    p.add_argument('--gamma-sparse', type=float, default=0.1, help='L1 sparsity weight')
    p.add_argument('--max-iter', type=int, default=100, help='Max iterations for factorization')
    p.add_argument('--tolerance-degrees', type=float, default=10.0, help='Tolerance for DOA accuracy (deg)')
    p.add_argument('--n-sources', type=int, default=1, help='Number of sources to localize')
    p.add_argument('--n-test-examples', type=int, default=1000, help='Max number of test examples')

    # Audio / TF parameters (kept in sync with defaults)
    p.add_argument('--sample-rate', type=int, default=16000)
    p.add_argument('--freq-min', type=float, default=500.0)
    p.add_argument('--freq-max', type=float, default=1500.0)

    # Angle filtering (optional)
    p.add_argument('--angle-min', type=float, default=None, help='Minimum angle (deg) to include in evaluation')
    p.add_argument('--angle-max', type=float, default=None, help='Maximum angle (deg) to include in evaluation')

    # Hardware and verbosity
    p.add_argument('--device', type=str, default='cpu', help="'cpu', 'cuda', or 'mps'")
    p.add_argument('-v', '--verbose', action='store_true', help='Verbose logging')

    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    setup_logging(args.verbose)
    logger = logging.getLogger(__name__)

    tf_path = Path(args.tf_path)
    speech_root = Path(args.speech_data_root)
    
    # For Configuration C: use separate USM and test data sources if provided
    usm_root = Path(args.usm_data_root) if args.usm_data_root else speech_root
    test_root = Path(args.test_data_root) if args.test_data_root else speech_root
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not tf_path.exists():
        logger.error(f"TF file not found: {tf_path}")
        return 1
    if not speech_root.exists():
        logger.error(f"Speech data root not found: {speech_root}")
        return 1
    if not usm_root.exists():
        logger.error(f"USM data root not found: {usm_root}")
        return 1
    if not test_root.exists():
        logger.error(f"Test data root not found: {test_root}")
        return 1
        
    logger.info(f"USM training data: {usm_root}")
    logger.info(f"Test data: {test_root}")

    # Build configuration
    config = NMFConfig(
        sample_rate=args.sample_rate,
        freq_min=args.freq_min,
        freq_max=args.freq_max,
        beta=args.beta,
        lambda_group=args.lambda_group,
        gamma_sparse=args.gamma_sparse,
        max_iter=args.max_iter,
        tolerance_degrees=args.tolerance_degrees,
        n_test_examples=args.n_test_examples,
        device=args.device,
        use_90deg_only=not args.use_all_angles_for_usm,  # Disable 90deg-only if flag set
    )

    # Run pipeline with pre-computed TFs and separate USM/test data
    pipeline = NMFLocalizationPipeline(config)
    
    # Load pre-trained USM if provided
    usm_path = Path(args.usm_path) if args.usm_path else None
    if usm_path and usm_path.exists():
        logger.info(f"=== USING PRE-TRAINED USM ===")
        logger.info(f"USM model: {usm_path}")
        pipeline.usm_trainer.load_model(str(usm_path))
        pipeline.usm_model = pipeline.usm_trainer.W  # Access W attribute directly
        logger.info(f"USM loaded: shape {pipeline.usm_model.shape}")
    
    # Log data source configuration
    if test_root != usm_root:
        logger.info("=== CROSS-DOMAIN CONFIGURATION ===")
        logger.info(f"USM training data: {usm_root}")
        logger.info(f"Test data: {test_root}")
    else:
        logger.info("=== STANDARD CONFIGURATION ===")
        logger.info(f"USM and test data: {speech_root}")
    
    try:
        results = pipeline.run_full_experiment(
            data_root="unused_when_tf_path_is_set",
            output_dir=out_dir,
            n_sources=args.n_sources,
            tf_path=tf_path,
            speech_data_root=usm_root,     # USM training data
            test_data_root=test_root,      # Test data (may be different)
            save_models=True,
            angle_min=args.angle_min,
            angle_max=args.angle_max,
        )
    except Exception as e:
        logger.exception(f"Experiment failed: {e}")
        return 1

    eval_res = results['stages']['evaluation']['results']
    logger.info("\n=== FINAL RESULTS ===")
    logger.info(f"Accuracy: {eval_res['accuracy']:.1f}% | Mean Error: {eval_res['mean_error']:.1f}° | Per-Source Acc: {eval_res['per_source_accuracy']:.1f}%")
    logger.info(f"Saved under: {out_dir}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
